---
title: "Fly Data"
author: "Jesse Leigh Patsolic"
date: '`r Sys.Date()`'
output:
  html_document:
    fig_caption: yes
    fig_height: 8
    fig_width: 8
    highlight: pygments
    number_sections: yes
    theme: cerulean
    toc: yes
    toc_depth: 1
---

```{r knitOPTS, include=FALSE}
knitr::opts_chunk$set(dev = "png")
```

<!--
### ### INITIAL COMMENTS HERE ###
###
### Jesse Leigh Patsolic 
### 2018 <Jesse.L.Patsolic@alumni.wfu.edu>
### S.D.G 
#
-->

```{r render, eval=FALSE, echo=FALSE}
## You can build this notebook by running this code block.
require(rmarkdown)
require(mbstructure)
require(rerf)
require(mclust)
require(meda)
require(raster)
require(irlba)
require(viridis)
require(dendextend)
set.seed(16661)
rmarkdown::render("flyData.Rmd")
system('open flyData.html')
```

## Setup

```{r, eval = FALSE}
require(devtools)
devtools::install_github("youngser/mbstructure")
```


## Data Preparation 

```{r}
data(MBconnectome)
```

## Download data

```{r}
leftA <- read.table("https://raw.githubusercontent.com/neurodata/graspy/graphmodel/graspy/datasets/drosophila/left_adjacency.csv", header = FALSE, sep = " ")

rightA <- read.table("https://raw.githubusercontent.com/neurodata/graspy/graphmodel/graspy/datasets/drosophila/right_adjacency.csv", header = FALSE, sep = " ")

leftLabels <- read.csv("https://raw.githubusercontent.com/neurodata/graspy/graphmodel/graspy/datasets/drosophila/left_cell_labels.csv", header = FALSE)

rightLabels <- read.csv("https://raw.githubusercontent.com/neurodata/graspy/graphmodel/graspy/datasets/drosophila/right_cell_labels.csv", header = FALSE)
```

## Embed

```{r}
X <- as.matrix(rightA)
Xb <- X
Xb[which(Xb > 0)] <- 1

Xase <- irlba(Xb, nv = 5)

Xl <- Xase$u
Xr <- Xase$v

Xls <- Xase$u / Xase$d
Xrs <- Xase$v / Xase$d

XX <- cbind(Xl, Xr)
XXs <- cbind(Xls, Xrs)

dim(XX)
```

## Run Urerf

NB: URerF by default normalizes the data before running.  This seems to
"smooth" the output matrices.

```{r, results = "hide"}
XX.fit  <- Urerf(XX, trees = 500, normalizeData = TRUE)
XXs.fit <- Urerf(XX, trees = 500, normalizeData = TRUE)

simM <- XX.fit$sim
dsimM <- 1 - simM
```

## Plot Affinity Matrices
```{r}
plot(raster(simM), col = viridis(255), main = "Similarity")
plot(raster(dsimM), col = viridis(255), main = "Dissimilarity")
```


```{r}
write.table(file = "similarityMatrix.csv", simM, row.names = FALSE, col.names = FALSE, sep = ",")
write.table(file = "dissimilarityMatrix.csv", 1 - simM, row.names = FALSE, col.names = FALSE, sep = ",")
```

##  Embed the similarity

```{r}
Y <- irlba(simM, nv = 4)
```

```{r}
pairs(Y$u, col = scales::alpha(viridis(4)[as.numeric(rightLabels[[1]])], 0.55), pch = 16, cex = 0.75)
```

# Mclust

## Fit Mclust

```{r, results = "hide"}
m.fit <-  Mclust(Y$u)
```

## Plot Mclust BIC and Classifications

```{r}
plot(m.fit, what = c("BIC"))
plot(m.fit, what = c("classification"))
```

## ARI

```{r ari}
mclust::adjustedRandIndex(rightLabels[[1]], m.fit$classification)
```

## Permutation test

```{r permTest}
mi <- 1e4
ARI <- vector("numeric", mi)

for(i in 1:mi){
  set.seed(i)
  ARI[i] <-  
    mclust::adjustedRandIndex(rightLabels[[1]], 
      sample(m.fit$classification, replace= FALSE))
}
```

```{r}
plot(histogram(ARI, bin = "Scott", main = "Permutation test of null-distribution"))
```


# Hclust

```{r}
Ydist <- as.dist(dsimM)
h.fit <- hclust(Ydist, method = "average")

plot(h.fit)
plot(as.dendrogram(h.fit))

hclust.labels4 <- cutree(h.fit, k = 4)
hclust.labels5 <- cutree(h.fit, k = 5)
hclust.labels6 <- cutree(h.fit, k = 6)
```

## ARI

```{r}
mclust::adjustedRandIndex(rightLabels[[1]], hclust.labels4)
mclust::adjustedRandIndex(rightLabels[[1]], hclust.labels5)
mclust::adjustedRandIndex(rightLabels[[1]], hclust.labels6)
```

## Permutation test

```{r permTest-hclust}
mi <- 1e4
ARIh <- vector("numeric", mi)

for(i in 1:mi){
  set.seed(i)
  ARIh[i] <-  
    mclust::adjustedRandIndex(rightLabels[[1]], 
      sample(hclust.labels5, replace= FALSE))
}
```

```{r}
plot(histogram(ARIh, bin = "Scott", main = "Permutation test of null-distribution"))
```

```{r}
dend5 <- as.dendrogram(h.fit)

dend5 %>% set("labels", hclust.labels5) %>% 
  color_branches(col = viridis(5)[hclust.labels5]) %>% 
  sort %>%
  plot()

heatmap(as.matrix(Ydist), Rowv = dend5, labCol = hclust.labels5, labRow = hclust.labels5, col = viridis(255))
```


<!--
#   Time:
##  Working status:
### Comments:
--> 

